### ISSUE TITLE
Cannot Render it in Eclipse Project

### ISSUE THREAD

**Issue by sha2nkk** [FilipPudak/ProgressPieView#13]
Hi,
Nice Plugin...I saw your sample app...I want to implement the same in my project but it is in eclipse..it gives error...in init method...can you provide Eclipse version of it library...thanks

**Comment by FilipPudak** [comment]
Sorry but since Google itself is moving away from Eclipse as IDE of choice, there is no ambition to support it for this lib. It's time to move on to Android Studio.
