### ISSUE TITLE
OnProgressCompleted verification

### ISSUE THREAD

**Issue by pavlospt** [FilipPudak/ProgressPieView#2]
Hello mate! Nice work there! 
Just have to point something out in your example! I think you need to set up a boolean flag and check if the progressCompleted method has been reached and then if the progressChanged is called again remove the drawable that you set and enable the text!

**Comment by FilipPudak** [comment]
Hi,
Thanks for the comments. The idea behind the example was more as a showcase of what methods can be called and how, did not put much thought behind edge cases. Nice input, will make a change that reflects this behaviour you noted!
